### PR TITLE
Update CI settings

### PR DESCRIPTION
**Pull request by omus**
Note that Appveyor wasn't setup for this repo and only the outdated config file was present.

### CODE REVIEW

**Comment by omus** [comment]
I'll rebase once https://github.com/JuliaCloud/XMLDict.jl/pull/22 is merged

**Comment by mattBrzezinski** [comment]
> I'll rebase once #22 is merged

This merge request is #22? I think you mean #21 :P

**Review by mattBrzezinski — APPROVED** [review]

**Comment by omus** [comment]
Whoops, I did mean #21. So many PRs...

**Comment by omus** [comment]
I think I'll switch things around and rebase #21

**Pull request merged**
